version: '3.7'
services:
  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 8000:8000
    volumes:
      - ./packages/backend:/usr/src/app/packages/backend
      - /usr/src/app/packages/backend/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: yarn backend:dev

  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 3000:3000
    volumes:
      - ./packages/portfolio:/usr/src/app/packages/portfolio
      - /usr/src/app/packages/portfolio/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: yarn portfolio:start

networks:
  app-network:
    driver: bridge
