version: '3.7'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - app-network
    logging:
      driver: none

  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge
