version: '3.7'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    # restart: always
    networks:
      - app-network
    logging:
      driver: none
  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 8000:8000
    volumes:
      - ./packages/backend:/usr/src/app/packages/backend
      - /usr/src/app/packages/backend/node_modules
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: yarn backend:dev

  portfolio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/packages/portfolio/node_modules
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: yarn portfolio:start

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/packages/frontend/node_modules
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: yarn frontend:start

networks:
  app-network:
    driver: bridge
